#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_billetterie:
    path: /billetterie/triParJours/{day}
    controller: App\Controller\triParJours::recupBillet

app_billetterie_joueur:
    path: /billetterie/triParJoueur/{player}
    controller: App\Controller\triParJoueur::recupBilletJoueur
    
app_liste_joueur:
    path: /billetterie/liste_joueur
    controller: App\Controller\joueurController::recupJoueur

app_decrease:
    path: /billetterie/decrease/{billetId}
    controller: App\Controller\billetController::decreaseQuantity
    defaults:
        billetId: 1

app_findById:
    path: /billetterie/getById/{billetId}
    controller: App\Controller\billetController::getById
    defaults:
        billetId: 1